[package]
name = "ap_display"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
tokio-tungstenite = "0.19"
url = "2.3"
futures-util = "0.3"
image = "0.24"
minifb = "0.24"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }